services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    entrypoint: sleep infinity
    working_dir: /var/www/html
    depends_on:
      - db
      - redis
    ports:
      - "80:80"
      - "5173:5173"
      - "6001:6001"
    networks:
      - app-network
  db:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - app-network
  phpunit:
    image: php:8.2-cli
    container_name: laravel_phpunit
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
